learning_rate: 0.001
num_epochs: 15 # Global, but can be overridden by training_params
batch_size: 32

data_params:
  quantile_levels: 20 # Default quantile level for binarization

rtm_params:
  number_of_clauses: 10000 
  T: 1000                  # Modified for normalized Y
  s: 3.0                   
  boost_true_positive_feedback: 1 
  number_of_state_bits: 8

tmu_rtm_model:
  number_of_clauses: 5000
  T: 800
  s: 5.0
  weighted_clauses: True
  n_jobs: -1 # Use all available cores

training_params:
  num_epochs: 15 
  early_stopping_patience: 5
  model_save_name_prefix: "rtm_denoiser_c10k_T1k_s3_Ynorm"