learning_rate: 0.001
num_epochs: 15 # Globale, ma può essere sovrascritto da training_params
batch_size: 32
rtm_params:
  number_of_clauses: 10000 
  T: 1000                  # MODIFICATO per Y normalizzato
  s: 3.0                   
  boost_true_positive_feedback: 1 
  number_of_state_bits: 8

training_params:
  num_epochs: 15 
  early_stopping_patience: 5
  model_save_name_prefix: "rtm_denoiser_c10k_T1k_s3_Ynorm"